In [ ]:
!pip install nltk

In [1]:
import nltk
import pandas as pd
import json
import os 
import sys
import requests
import datetime as dt
import time
import zlib
import msgpack
import os.path
import yfinance as yfin
from pandas_datareader import data as pdr

In [ ]:
nltk.download('vader_lexicon') # one time only


In [6]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer


In [7]:
# name the vader analysis tool
vader = SentimentIntensityAnalyzer() 


In [8]:
# sample
sample = 'I really dont\' love NVIDIA'

In [9]:
SentimentIntensityAnalyzer().polarity_scores(sample)

{'neg': 0.549, 'neu': 0.451, 'pos': 0.0, 'compound': -0.5642}

In [10]:
# import files from src
sys.path.insert(0, "src")
from pathlib import Path
import numpy as np

In [11]:
# define the location of the input file

file_augmento_topics = Path("../Project-2/Project_2/augmento_topics.msgpack.zlib")
isExist = os.path.exists(file_augmento_topics)
print(isExist)

True


In [12]:
# load the topics
with open(file_augmento_topics, "rb") as f:
    augmento_topics = msgpack.unpackb(zlib.decompress(f.read()))

In [13]:
file_augmento_data = Path('../Project-2/Project_2/augmento_data.msgpack.zlib')
isExist = os.path.exists(file_augmento_data)
print(isExist)

True


In [ ]:
print(json.dumps(augmento_topics))

In [72]:
# load the data
with open(file_augmento_data, "rb") as f:
    augmento_data = msgpack.unpackb(zlib.decompress(f.read()))
    t_aug_data = np.array([el["t_epoch"] for el in augmento_data], dtype=np.float64)
    aug_data = np.array([el["counts"] for el in augmento_data], dtype=np.int32)

In [73]:
t_aug_data

array([1.4832288e+09, 1.4833152e+09, 1.4834016e+09, ..., 1.6537824e+09,
       1.6538688e+09, 1.6539552e+09])

In [14]:
file_eth_data = Path('../Project-2/Project_2/eth_data.msgpack.zlib')
isExist = os.path.exists(file_eth_data)
print(isExist)

True


In [30]:
	# load the price data
with open(file_eth_data, "rb") as f:
    temp = msgpack.unpackb(zlib.decompress(f.read()))
    eth_data = pd.DataFrame(temp['data'])
    t_price_data = np.array('data' in temp).astype('float64')
	#price_data = np.array([el["open"] for el in temp], dtype=np.float64)
    price_data = np.array(eth_data['Close'], dtype=np.float64)

In [31]:
t_price_data

array(1.)

In [34]:
eth_data = pd.DataFrame(temp['data'])

In [41]:
display(eth_data.head())
display(eth_data.tail())

Date       Close
0  2017-11-09T00:00:00.000Z  320.884003
1  2017-11-10T00:00:00.000Z  299.252991
2  2017-11-11T00:00:00.000Z  314.681000
3  2017-11-12T00:00:00.000Z  307.907990
4  2017-11-13T00:00:00.000Z  316.716003

Date        Close
1661  2022-05-28T00:00:00.000Z  1757.941772
1662  2022-05-29T00:00:00.000Z  1812.031006
1663  2022-05-30T00:00:00.000Z  1996.441284
1664  2022-05-31T00:00:00.000Z  1942.328003
1665  2022-06-01T00:00:00.000Z  1823.569336

In [39]:
price = np.array(eth_data['Close'], dtype=np.float64)
price

array([ 320.88400269,  299.25299072,  314.68099976, ..., 1996.44128418,
       1942.32800293, 1823.56933594])

In [66]:
t_price = eth_data['Date'].to_numpy().astype('datetime64')
print(t_price.dtype)

datetime64[ms]


C:\Users\kraso\AppData\Local\Temp\ipykernel_13016\1452870568.py:1: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  t_price = eth_data['Date'].to_numpy().astype('datetime64')


In [54]:
from dateutil import parser

In [69]:
t_price_ = t_price.astype('float64')

In [70]:
t_price_

array([1.5101856e+12, 1.5102720e+12, 1.5103584e+12, ..., 1.6538688e+12,
       1.6539552e+12, 1.6540416e+12])